//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epanet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epanet.Properties.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation halted..
        /// </summary>
        internal static string ERR1000 {
            get {
                return ResourceManager.GetString("ERR1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error 101: insufficient memory available..
        /// </summary>
        internal static string ERR101 {
            get {
                return ResourceManager.GetString("ERR101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error 102: no network data available..
        /// </summary>
        internal static string ERR102 {
            get {
                return ResourceManager.GetString("ERR102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error 103: hydraulics not initialized..
        /// </summary>
        internal static string ERR103 {
            get {
                return ResourceManager.GetString("ERR103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error 104: no hydraulics for water quality analysis..
        /// </summary>
        internal static string ERR104 {
            get {
                return ResourceManager.GetString("ERR104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error 105: water quality not initialized..
        /// </summary>
        internal static string ERR105 {
            get {
                return ResourceManager.GetString("ERR105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error 106: no results saved to report on..
        /// </summary>
        internal static string ERR106 {
            get {
                return ResourceManager.GetString("ERR106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error 107: hydraulics supplied from external file..
        /// </summary>
        internal static string ERR107 {
            get {
                return ResourceManager.GetString("ERR107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error 108: cannot use external file while hydraulics solver is active..
        /// </summary>
        internal static string ERR108 {
            get {
                return ResourceManager.GetString("ERR108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error 109: cannot change time parameter when solver is active..
        /// </summary>
        internal static string ERR109 {
            get {
                return ResourceManager.GetString("ERR109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error 110: cannot solve network hydraulic equations..
        /// </summary>
        internal static string ERR110 {
            get {
                return ResourceManager.GetString("ERR110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error 120: cannot solve water quality transport equations..
        /// </summary>
        internal static string ERR120 {
            get {
                return ResourceManager.GetString("ERR120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 200: one or more errors in input file..
        /// </summary>
        internal static string ERR200 {
            get {
                return ResourceManager.GetString("ERR200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 201: syntax error in following line of [{0}] section: {1}.
        /// </summary>
        internal static string ERR201 {
            get {
                return ResourceManager.GetString("ERR201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 202: {0} {1} contains illegal numeric value..
        /// </summary>
        internal static string ERR202 {
            get {
                return ResourceManager.GetString("ERR202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 203: {0} {1} refers to undefined node..
        /// </summary>
        internal static string ERR203 {
            get {
                return ResourceManager.GetString("ERR203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 204: {0} {1} refers to undefined link..
        /// </summary>
        internal static string ERR204 {
            get {
                return ResourceManager.GetString("ERR204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 205: {0} {1} refers to undefined time pattern..
        /// </summary>
        internal static string ERR205 {
            get {
                return ResourceManager.GetString("ERR205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 206: {0} {1} refers to undefined curve..
        /// </summary>
        internal static string ERR206 {
            get {
                return ResourceManager.GetString("ERR206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 207: {0} {1} attempts to control a CV..
        /// </summary>
        internal static string ERR207 {
            get {
                return ResourceManager.GetString("ERR207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 208: {0} specified for undefined Node {1}..
        /// </summary>
        internal static string ERR208 {
            get {
                return ResourceManager.GetString("ERR208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 209: illegal {0} value for Node {1}..
        /// </summary>
        internal static string ERR209 {
            get {
                return ResourceManager.GetString("ERR209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 210: {0} specified for undefined Link {1}..
        /// </summary>
        internal static string ERR210 {
            get {
                return ResourceManager.GetString("ERR210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 211: illegal {0} value for Link {1}..
        /// </summary>
        internal static string ERR211 {
            get {
                return ResourceManager.GetString("ERR211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 212: trace node {0} {1} is undefined..
        /// </summary>
        internal static string ERR212 {
            get {
                return ResourceManager.GetString("ERR212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 213: illegal option value in [{0}] section: {1}.
        /// </summary>
        internal static string ERR213 {
            get {
                return ResourceManager.GetString("ERR213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 214: following line of [{0}] section contains too many characters:.
        /// </summary>
        internal static string ERR214 {
            get {
                return ResourceManager.GetString("ERR214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 215: {0} {1} is a duplicate ID..
        /// </summary>
        internal static string ERR215 {
            get {
                return ResourceManager.GetString("ERR215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 216: {0} data specified for undefined Pump {1}..
        /// </summary>
        internal static string ERR216 {
            get {
                return ResourceManager.GetString("ERR216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 217: invalid {0} data for Pump {1}..
        /// </summary>
        internal static string ERR217 {
            get {
                return ResourceManager.GetString("ERR217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 219: {0} {1} illegally connected to a tank..
        /// </summary>
        internal static string ERR219 {
            get {
                return ResourceManager.GetString("ERR219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 220: {0} {1} illegally connected to another valve..
        /// </summary>
        internal static string ERR220 {
            get {
                return ResourceManager.GetString("ERR220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 222: {0} {1} has same start and end nodes..
        /// </summary>
        internal static string ERR222 {
            get {
                return ResourceManager.GetString("ERR222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 201: syntax error in following line of [{0}] section:.
        /// </summary>
        internal static string ERR223 {
            get {
                return ResourceManager.GetString("ERR223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 224: no tanks or reservoirs in network..
        /// </summary>
        internal static string ERR224 {
            get {
                return ResourceManager.GetString("ERR224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 225: invalid lower/upper levels for Tank {0}..
        /// </summary>
        internal static string ERR225 {
            get {
                return ResourceManager.GetString("ERR225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 226: no head curve supplied for Pump {0}..
        /// </summary>
        internal static string ERR226 {
            get {
                return ResourceManager.GetString("ERR226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 227: invalid head curve for Pump {0}..
        /// </summary>
        internal static string ERR227 {
            get {
                return ResourceManager.GetString("ERR227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 233: Node {0} is unconnected..
        /// </summary>
        internal static string ERR233 {
            get {
                return ResourceManager.GetString("ERR233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 240: {0} {1} refers to undefined source..
        /// </summary>
        internal static string ERR240 {
            get {
                return ResourceManager.GetString("ERR240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 241: {0} {1} refers to undefined control..
        /// </summary>
        internal static string ERR241 {
            get {
                return ResourceManager.GetString("ERR241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 250: function call contains invalid format..
        /// </summary>
        internal static string ERR250 {
            get {
                return ResourceManager.GetString("ERR250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 251: function call contains invalid parameter code..
        /// </summary>
        internal static string ERR251 {
            get {
                return ResourceManager.GetString("ERR251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error 301: identical file names..
        /// </summary>
        internal static string ERR301 {
            get {
                return ResourceManager.GetString("ERR301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error 302: cannot open input file..
        /// </summary>
        internal static string ERR302 {
            get {
                return ResourceManager.GetString("ERR302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error 303: cannot open report file..
        /// </summary>
        internal static string ERR303 {
            get {
                return ResourceManager.GetString("ERR303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error 304: cannot open binary output file..
        /// </summary>
        internal static string ERR304 {
            get {
                return ResourceManager.GetString("ERR304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error 305: cannot open hydraulics file..
        /// </summary>
        internal static string ERR305 {
            get {
                return ResourceManager.GetString("ERR305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error 306: hydraulics file does not match network data..
        /// </summary>
        internal static string ERR306 {
            get {
                return ResourceManager.GetString("ERR306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error 307: cannot read hydraulics file..
        /// </summary>
        internal static string ERR307 {
            get {
                return ResourceManager.GetString("ERR307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error 308: cannot save results to file..
        /// </summary>
        internal static string ERR308 {
            get {
                return ResourceManager.GetString("ERR308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error 309: cannot save results to report file..
        /// </summary>
        internal static string ERR309 {
            get {
                return ResourceManager.GetString("ERR309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property [{0}] already exists in the map..
        /// </summary>
        internal static string ERR700 {
            get {
                return ResourceManager.GetString("ERR700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property [{0}] doesn&apos;t exists in the map..
        /// </summary>
        internal static string ERR701 {
            get {
                return ResourceManager.GetString("ERR701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 201: syntax error in following line of.
        /// </summary>
        internal static string R_ERR201 {
            get {
                return ResourceManager.GetString("R_ERR201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 202: illegal numeric value in following line of.
        /// </summary>
        internal static string R_ERR202 {
            get {
                return ResourceManager.GetString("R_ERR202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 203: undefined node in following line of.
        /// </summary>
        internal static string R_ERR203 {
            get {
                return ResourceManager.GetString("R_ERR203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 204: undefined link in following line of.
        /// </summary>
        internal static string R_ERR204 {
            get {
                return ResourceManager.GetString("R_ERR204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error 207: attempt to control a CV in following line of.
        /// </summary>
        internal static string R_ERR207 {
            get {
                return ResourceManager.GetString("R_ERR207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: System unbalanced at {0} hrs..
        /// </summary>
        internal static string WARN01 {
            get {
                return ResourceManager.GetString("WARN01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Maximum trials exceeded at {0} hrs. System may be unstable..
        /// </summary>
        internal static string WARN02 {
            get {
                return ResourceManager.GetString("WARN02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Node {0} disconnected at {1} hrs.
        /// </summary>
        internal static string WARN03a {
            get {
                return ResourceManager.GetString("WARN03a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: {d} additional nodes disconnected at {1} hrs.
        /// </summary>
        internal static string WARN03b {
            get {
                return ResourceManager.GetString("WARN03b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: System disconnected because of Link {0}.
        /// </summary>
        internal static string WARN03c {
            get {
                return ResourceManager.GetString("WARN03c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Pump {0} {1} at {2} hrs..
        /// </summary>
        internal static string WARN04 {
            get {
                return ResourceManager.GetString("WARN04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: {0} {1} {2} at {3} hrs..
        /// </summary>
        internal static string WARN05 {
            get {
                return ResourceManager.GetString("WARN05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Negative pressures at {0} hrs..
        /// </summary>
        internal static string WARN06 {
            get {
                return ResourceManager.GetString("WARN06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: System hydraulically unbalanced..
        /// </summary>
        internal static string WARN1 {
            get {
                return ResourceManager.GetString("WARN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: System may be hydraulically unstable..
        /// </summary>
        internal static string WARN2 {
            get {
                return ResourceManager.GetString("WARN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: System disconnected..
        /// </summary>
        internal static string WARN3 {
            get {
                return ResourceManager.GetString("WARN3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Pumps cannot deliver enough flow or head..
        /// </summary>
        internal static string WARN4 {
            get {
                return ResourceManager.GetString("WARN4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Valves cannot deliver enough flow..
        /// </summary>
        internal static string WARN5 {
            get {
                return ResourceManager.GetString("WARN5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: System has negative pressures..
        /// </summary>
        internal static string WARN6 {
            get {
                return ResourceManager.GetString("WARN6", resourceCulture);
            }
        }
    }
}
