//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epanet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epanet.Properties.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///... EPANET Version 2.0
        ///.
        /// </summary>
        public static string FMT01 {
            get {
                return ResourceManager.GetString("FMT01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  o Retrieving network data ....
        /// </summary>
        public static string FMT02 {
            get {
                return ResourceManager.GetString("FMT02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// Correct syntax is:
        /// epanet &lt;input file&gt; &lt;output file&gt;
        ///.
        /// </summary>
        public static string FMT03 {
            get {
                return ResourceManager.GetString("FMT03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Cannot use duplicate file names..
        /// </summary>
        public static string FMT04 {
            get {
                return ResourceManager.GetString("FMT04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Cannot open input file.
        /// </summary>
        public static string FMT05 {
            get {
                return ResourceManager.GetString("FMT05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Cannot open report file.
        /// </summary>
        public static string FMT06 {
            get {
                return ResourceManager.GetString("FMT06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Cannot open output file.
        /// </summary>
        public static string FMT07 {
            get {
                return ResourceManager.GetString("FMT07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Cannot open temporary output file.
        /// </summary>
        public static string FMT08 {
            get {
                return ResourceManager.GetString("FMT08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///... EPANET completed.
        ///.
        /// </summary>
        public static string FMT09 {
            get {
                return ResourceManager.GetString("FMT09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///... EPANET completed. There are warnings.
        ///.
        /// </summary>
        public static string FMT10 {
            get {
                return ResourceManager.GetString("FMT10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving network data....
        /// </summary>
        public static string FMT100 {
            get {
                return ResourceManager.GetString("FMT100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computing hydraulics ....
        /// </summary>
        public static string FMT101 {
            get {
                return ResourceManager.GetString("FMT101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computing water quality ....
        /// </summary>
        public static string FMT102 {
            get {
                return ResourceManager.GetString("FMT102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving results to file....
        /// </summary>
        public static string FMT103 {
            get {
                return ResourceManager.GetString("FMT103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis begun {0}.
        /// </summary>
        public static string FMT104 {
            get {
                return ResourceManager.GetString("FMT104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis ended {0}.
        /// </summary>
        public static string FMT105 {
            get {
                return ResourceManager.GetString("FMT105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///... EPANET completed. There are errors.
        ///.
        /// </summary>
        public static string FMT11 {
            get {
                return ResourceManager.GetString("FMT11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  o Computing hydraulics ....
        /// </summary>
        public static string FMT14 {
            get {
                return ResourceManager.GetString("FMT14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  o Computing water quality ....
        /// </summary>
        public static string FMT15 {
            get {
                return ResourceManager.GetString("FMT15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  o Transferring results to file.
        /// </summary>
        public static string FMT16 {
            get {
                return ResourceManager.GetString("FMT16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  o Writing output report to.
        /// </summary>
        public static string FMT17 {
            get {
                return ResourceManager.GetString("FMT17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Page 1.
        /// </summary>
        public static string FMT18 {
            get {
                return ResourceManager.GetString("FMT18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Input Data File.
        /// </summary>
        public static string FMT19 {
            get {
                return ResourceManager.GetString("FMT19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Number of Junctions.
        /// </summary>
        public static string FMT20 {
            get {
                return ResourceManager.GetString("FMT20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Number of Reservoirs.
        /// </summary>
        public static string FMT21a {
            get {
                return ResourceManager.GetString("FMT21a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Number of Tanks.
        /// </summary>
        public static string FMT21b {
            get {
                return ResourceManager.GetString("FMT21b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Number of Pipes.
        /// </summary>
        public static string FMT22 {
            get {
                return ResourceManager.GetString("FMT22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Number of Pumps.
        /// </summary>
        public static string FMT23 {
            get {
                return ResourceManager.GetString("FMT23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Number of Valves.
        /// </summary>
        public static string FMT24 {
            get {
                return ResourceManager.GetString("FMT24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Headloss Formula.
        /// </summary>
        public static string FMT25 {
            get {
                return ResourceManager.GetString("FMT25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Hydraulic Timestep.
        /// </summary>
        public static string FMT26 {
            get {
                return ResourceManager.GetString("FMT26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Hydraulic Accuracy.
        /// </summary>
        public static string FMT27 {
            get {
                return ResourceManager.GetString("FMT27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Status Check Frequency.
        /// </summary>
        public static string FMT27a {
            get {
                return ResourceManager.GetString("FMT27a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Maximum Trials Checked.
        /// </summary>
        public static string FMT27b {
            get {
                return ResourceManager.GetString("FMT27b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Damping Limit Threshold.
        /// </summary>
        public static string FMT27c {
            get {
                return ResourceManager.GetString("FMT27c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Maximum Trials.
        /// </summary>
        public static string FMT28 {
            get {
                return ResourceManager.GetString("FMT28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Quality Analysis.
        /// </summary>
        public static string FMT29 {
            get {
                return ResourceManager.GetString("FMT29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Quality Analysis.
        /// </summary>
        public static string FMT30 {
            get {
                return ResourceManager.GetString("FMT30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Quality Analysis.
        /// </summary>
        public static string FMT31 {
            get {
                return ResourceManager.GetString("FMT31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Quality Analysis.
        /// </summary>
        public static string FMT32 {
            get {
                return ResourceManager.GetString("FMT32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Water Quality.
        /// </summary>
        public static string FMT33 {
            get {
                return ResourceManager.GetString("FMT33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Water Quality.
        /// </summary>
        public static string FMT34 {
            get {
                return ResourceManager.GetString("FMT34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Specific Gravity.
        /// </summary>
        public static string FMT36 {
            get {
                return ResourceManager.GetString("FMT36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Relative Kinematic Viscosity.
        /// </summary>
        public static string FMT37a {
            get {
                return ResourceManager.GetString("FMT37a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Relative Chemical Diffusivity.
        /// </summary>
        public static string FMT37b {
            get {
                return ResourceManager.GetString("FMT37b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Demand Multiplier.
        /// </summary>
        public static string FMT38 {
            get {
                return ResourceManager.GetString("FMT38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Total Duration.
        /// </summary>
        public static string FMT39 {
            get {
                return ResourceManager.GetString("FMT39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Reporting Criteria:.
        /// </summary>
        public static string FMT40 {
            get {
                return ResourceManager.GetString("FMT40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        No Nodes.
        /// </summary>
        public static string FMT41 {
            get {
                return ResourceManager.GetString("FMT41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        All Nodes.
        /// </summary>
        public static string FMT42 {
            get {
                return ResourceManager.GetString("FMT42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        Selected Nodes.
        /// </summary>
        public static string FMT43 {
            get {
                return ResourceManager.GetString("FMT43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        No Links.
        /// </summary>
        public static string FMT44 {
            get {
                return ResourceManager.GetString("FMT44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        All Links.
        /// </summary>
        public static string FMT45 {
            get {
                return ResourceManager.GetString("FMT45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        Selected Links.
        /// </summary>
        public static string FMT46 {
            get {
                return ResourceManager.GetString("FMT46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        with {0} below {1:F2} {2}.
        /// </summary>
        public static string FMT47 {
            get {
                return ResourceManager.GetString("FMT47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        with {0} above {1:F2} {2}.
        /// </summary>
        public static string FMT48 {
            get {
                return ResourceManager.GetString("FMT48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydraulic Status:.
        /// </summary>
        public static string FMT49 {
            get {
                return ResourceManager.GetString("FMT49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,10}: Tank {1} is {2} at {3:F2} {4}.
        /// </summary>
        public static string FMT50 {
            get {
                return ResourceManager.GetString("FMT50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,10}: Reservoir {1} is {2}.
        /// </summary>
        public static string FMT51 {
            get {
                return ResourceManager.GetString("FMT51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,10}: {1} {2} {3}.
        /// </summary>
        public static string FMT52 {
            get {
                return ResourceManager.GetString("FMT52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,10}: {1} {2} changed from {3} to {4}.
        /// </summary>
        public static string FMT53 {
            get {
                return ResourceManager.GetString("FMT53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,10}: {1} {2} changed by {3} {4} control.
        /// </summary>
        public static string FMT54 {
            get {
                return ResourceManager.GetString("FMT54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,10}: {1} {2} changed by timer control.
        /// </summary>
        public static string FMT55 {
            get {
                return ResourceManager.GetString("FMT55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             {0} {1} setting changed to {2:F2}.
        /// </summary>
        public static string FMT56 {
            get {
                return ResourceManager.GetString("FMT56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             {0} {1} switched from {2} to {3}.
        /// </summary>
        public static string FMT57 {
            get {
                return ResourceManager.GetString("FMT57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,10}: Balanced after {1} trials.
        /// </summary>
        public static string FMT58 {
            get {
                return ResourceManager.GetString("FMT58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,10}: Unbalanced after {1} trials (flow change = {2:F6}).
        /// </summary>
        public static string FMT59 {
            get {
                return ResourceManager.GetString("FMT59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             Max. flow imbalance is {0:F4} {1} at Node {2}.
        /// </summary>
        public static string FMT60a {
            get {
                return ResourceManager.GetString("FMT60a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             Max. head imbalance is {0:F4} {1} at Link {2}.
        /// </summary>
        public static string FMT60b {
            get {
                return ResourceManager.GetString("FMT60b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,10}: Valve {1} caused ill-conditioning.
        /// </summary>
        public static string FMT61 {
            get {
                return ResourceManager.GetString("FMT61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,10}: System ill-conditioned at node {1}.
        /// </summary>
        public static string FMT62 {
            get {
                return ResourceManager.GetString("FMT62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,10}: {1} {2} changed by rule {3}.
        /// </summary>
        public static string FMT63 {
            get {
                return ResourceManager.GetString("FMT63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,10}: Balancing the network:.
        /// </summary>
        public static string FMT64 {
            get {
                return ResourceManager.GetString("FMT64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             Trial {0,2}: relative flow change = {1:F6}.
        /// </summary>
        public static string FMT65 {
            get {
                return ResourceManager.GetString("FMT65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Usage:.
        /// </summary>
        public static string FMT71 {
            get {
                return ResourceManager.GetString("FMT71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to            Usage   Avg.     Kw-hr      Avg.      Peak      Cost.
        /// </summary>
        public static string FMT72 {
            get {
                return ResourceManager.GetString("FMT72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pump      Factor Effic.     {0}        Kw        Kw      /day.
        /// </summary>
        public static string FMT73 {
            get {
                return ResourceManager.GetString("FMT73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,38} Demand Charge: {1,9:F2}.
        /// </summary>
        public static string FMT74 {
            get {
                return ResourceManager.GetString("FMT74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,38} Total Cost:    {1,9:F2}.
        /// </summary>
        public static string FMT75 {
            get {
                return ResourceManager.GetString("FMT75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Node Results:.
        /// </summary>
        public static string FMT76 {
            get {
                return ResourceManager.GetString("FMT76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Results:.
        /// </summary>
        public static string FMT77 {
            get {
                return ResourceManager.GetString("FMT77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Results at {0} hrs:.
        /// </summary>
        public static string FMT78 {
            get {
                return ResourceManager.GetString("FMT78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Link Results:.
        /// </summary>
        public static string FMT79 {
            get {
                return ResourceManager.GetString("FMT79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Results:.
        /// </summary>
        public static string FMT80 {
            get {
                return ResourceManager.GetString("FMT80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Results at {0} hrs:.
        /// </summary>
        public static string FMT81 {
            get {
                return ResourceManager.GetString("FMT81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///  Page {0}    {1,60}
        ///.
        /// </summary>
        public static string FMT82 {
            get {
                return ResourceManager.GetString("FMT82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ******************************************************************.
        /// </summary>
        public static string LOG01 {
            get {
                return ResourceManager.GetString("LOG01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *                       E P A N E T  C#                          *.
        /// </summary>
        public static string LOG02 {
            get {
                return ResourceManager.GetString("LOG02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *                   Hydraulic and Water Quality                  *.
        /// </summary>
        public static string LOG03 {
            get {
                return ResourceManager.GetString("LOG03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *                   Analysis for Pipe Networks                   *.
        /// </summary>
        public static string LOG04 {
            get {
                return ResourceManager.GetString("LOG04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *                                                                *.
        /// </summary>
        public static string LOG05 {
            get {
                return ResourceManager.GetString("LOG05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ******************************************************************.
        /// </summary>
        public static string LOG06 {
            get {
                return ResourceManager.GetString("LOG06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function call.
        /// </summary>
        public static string t_FUNCCALL {
            get {
                return ResourceManager.GetString("t_FUNCCALL", resourceCulture);
            }
        }
    }
}
